//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int id { get; set; }

        public string imagen { get; set; }

        [Required(ErrorMessage = "El nombre es campo obligatorio")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El apellido es campo obligatorio")]
        public string apellido { get; set; }

        [Required(ErrorMessage = "El email es campo obligatorio")]
        public string email { get; set; }

        [Required(ErrorMessage = "La clave debe tener como mínimo 4 caracteres y como máximo 15")]
        [DataType(DataType.Password)]
        [MinLength(length: 4)]
        [MaxLength(length: 15)]
        public string clave { get; set; }

        public string rol { get; set; }
    }
}
